/**
 * Repères touristiques (5 à 7) par ville canonique du catalogue.
 * Clés = normalizeTextForSearch(nom affiché) : minuscules, sans accents.
 *
 * ⚠️ Logique figée : ne pas modifier ce fichier ni le flux associé (voir .cursor/rules/destination-iconic-places.mdc)
 * sauf demande explicite du créateur du projet.
 */
export const ICONIC_PLACES_CANONICAL = {
  paris: [
    "Tour Eiffel",
    "Musée du Louvre",
    "Cathédrale Notre-Dame de Paris",
    "Arc de triomphe & Champs-Élysées",
    "Musée d'Orsay",
    "Montmartre & basilique du Sacré-Cœur",
    "Quartier du Marais",
  ],
  lyon: [
    "Basilique Notre-Dame de Fourvière",
    "Vieux Lyon & traboules",
    "Parc de la Tête d'Or",
    "Place Bellecour",
    "Musée des Confluences",
    "La Croix-Rousse",
    "Théâtre gallo-romain de Fourvière",
  ],
  marseille: [
    "Vieux-Port",
    "Basilique Notre-Dame de la Garde",
    "Mucem",
    "Quartier du Panier",
    "Calanques de Marseille & Cassis",
    "Château d'If",
    "Corniche Kennedy",
  ],
  nice: [
    "Promenade des Anglais",
    "Vieux-Nice",
    "Colline du château",
    "Cours Saleya & marché",
    "Place Masséna",
    "Musée Matisse",
    "Cathédrale Sainte-Réparate",
  ],
  monaco: [
    "Palais princier",
    "Casino de Monte-Carlo & Opéra",
    "Port Hercule",
    "Cathédrale Notre-Dame-Immaculée",
    "Jardin exotique",
    "Musée océanographique",
    "Larvotto & plage",
  ],
  bordeaux: [
    "Place de la Bourse & miroir d'eau",
    "Cité du Vin",
    "Grosse Cloche & rue Saint-Pierre",
    "Cathédrale Saint-André",
    "Pont de pierre & quais",
    "Musée des Beaux-Arts",
    "Quartier des Chartrons",
  ],
  toulouse: [
    "Capitole & place du Capitole",
    "Basilique Saint-Sernin",
    "Cité de l'espace",
    "Canal du Midi",
    "Musée des Augustins",
    "Hôtel d'Assézat (Fondation Bemberg)",
    "Quartier Saint-Cyprien & Prairie des Filtres",
  ],
  lille: [
    "Grand'Place & Vieux-Lille",
    "Palais des Beaux-Arts",
    "Citadelle de Lille",
    "Hospice Comtesse",
    "Gare Saint-Sauveur & culture",
    "Parc de la Citadelle",
    "La Piscine — musée d'art & d'industrie (Roubaix)",
  ],
  nantes: [
    "Les Machines de l'île",
    "Château des ducs de Bretagne",
    "Cathédrale Saint-Pierre-et-Saint-Paul",
    "Île de Nantes & Trente Glorieuses",
    "Passage Pommeraye & Graslin",
    "Jardin des plantes",
    "Mémorial de l'abolition de l'esclavage",
  ],
  tokyo: [
    "Croisement de Shibuya",
    "Temple Senso-ji (Asakusa)",
    "Sanctuaire Meiji & Harajuku",
    "Quartier de Shinjuku",
    "Tokyo Skytree",
    "Marché Toyosu & sushi",
    "Palais impérial & jardins East",
  ],
  kyoto: [
    "Pavillon d'Or (Kinkaku-ji)",
    "Sanctuaire Fushimi Inari",
    "Arashiyama & bambouseraie",
    "Kiyomizu-dera",
    "Quartier de Gion",
    "Temple Ryoan-ji & jardin zen",
    "Château Nijo",
  ],
  osaka: [
    "Château d'Osaka",
    "Dotonbori & Namba",
    "Temple Shitenno-ji",
    "Umeda Sky Building",
    "Aquarium Kaiyukan",
    "Shinsekai & Tsūtenkaku",
    "Sanctuaire Sumiyoshi Taisha",
  ],
  seoul: [
    "Palais Gyeongbokgung",
    "Quartier hanok de Bukchon",
    "N Seoul Tower",
    "Marché Gwangjang",
    "Design Plaza Dongdaemun",
    "Promenade Cheonggyecheon",
    "Palais Changdeokgung & jardin secret",
  ],
  bangkok: [
    "Grand Palais & Wat Phra Kaew",
    "Wat Pho (Bouddha couché)",
    "Wat Arun",
    "Marché Chatuchak",
    "Khao San Road & vieille ville",
    "Wat Traimit & Chinatown Yaowarat",
    "Croisière sur les khlongs",
  ],
  singapore: [
    "Marina Bay Sands & Gardens by the Bay",
    "Sentosa & plages",
    "Quartier colonial & Raffles",
    "Chinatown & temple Thian Hock Keng",
    "Little India & Sri Veeramakaliamman",
    "Orchard Road",
    "Zoo de Singapour & Night Safari",
  ],
  bali: [
    "Ubud & rizières de Tegallalang",
    "Temple Lempuyang",
    "Temple Tanah Lot",
    "Temple d'Uluwatu & coucher de soleil",
    "Cascades de Tegenungan",
    "Plages de Seminyak & Canggu",
    "Marché d'Ubud & artisanat",
  ],
  jakarta: [
    "Monumen Nasional (Monas)",
    "Kota Tua & place Fatahillah",
    "Mosquée Istiqlal & cathédrale",
    "Taman Mini Indonesia Indah",
    "Musée national",
    "Quartier chinois Glodok",
    "Ancienne gare de Jakarta",
  ],
  beijing: [
    "Cité interdite",
    "Temple du Ciel",
    "Place Tian'anmen",
    "Palais d'été (Yiheyuan)",
    "Grande Muraille (Mutianyu ou Badaling)",
    "Parc Beihai",
    "Hutongs de Gulou / Shichahai",
  ],
  shanghai: [
    "The Bund & skyline de Pudong",
    "Tour Shanghai & Jin Mao",
    "Jardin Yu (Yuyuan)",
    "Nanjing Road",
    "Temple du dieu de la ville",
    "Xintiandi",
    "Musée de Shanghai",
  ],
  guangzhou: [
    "Tour du Mouton (Canton Tower)",
    "Temple des ancêtres de la famille Chen",
    "Île de Shamian",
    "Musée provincial du Guangdong",
    "Parc Yuexiu & statue des béliers",
    "Quartier Beijing Lu",
    "Temple du dieu du sud de la mer",
  ],
  "new york": [
    "Statue de la Liberté & Ellis Island",
    "Times Square",
    "Central Park",
    "Empire State Building",
    "Brooklyn Bridge",
    "Metropolitan Museum of Art (MET)",
    "Mémorial du 11-Septembre & One World Trade Center",
  ],
  "los angeles": [
    "Hollywood Walk of Fame & TCL Chinese Theatre",
    "Hollywood Sign (vue Griffith Observatory)",
    "Santa Monica Pier & Venice Beach",
    "Getty Center",
    "Beverly Hills & Rodeo Drive",
    "Universal Studios Hollywood",
    "Quartier musées (Miracle Mile)",
  ],
  "san francisco": [
    "Golden Gate Bridge",
    "Alcatraz & Fisherman's Wharf",
    "Cable cars & Nob Hill",
    "Quartier chinois",
    "Golden Gate Park & jardin japonais",
    "Pier 39 & otaries",
    "Mission District & fresques murales",
  ],
  miami: [
    "South Beach & quartier Art déco",
    "Wynwood Walls",
    "Villa Vizcaya & jardins",
    "Little Havana & Calle Ocho",
    "Key Biscayne & Crandon Park",
    "Bayside Marketplace",
    "Design District",
  ],
  chicago: [
    "Millennium Park & Cloud Gate",
    "Navy Pier",
    "Skydeck Willis Tower",
    "Art Institute of Chicago",
    "Field Museum",
    "Riverwalk & architecture en bateau",
    "360 Chicago (John Hancock)",
  ],
  toronto: [
    "CN Tower",
    "Îles de Toronto & ferry",
    "Marché St. Lawrence",
    "Casa Loma",
    "Distillery District",
    "Kensington Market",
    "Royal Ontario Museum",
  ],
  vancouver: [
    "Stanley Park & Seawall",
    "Granville Island",
    "Gastown & horloge à vapeur",
    "Pont suspendu de Capilano",
    "Musée d'anthropologie (UBC)",
    "English Bay & plage",
    "Quartier chinois",
  ],
  london: [
    "Big Ben & palais de Westminster",
    "Tower Bridge & Tour de Londres",
    "British Museum",
    "Buckingham Palace",
    "Covent Garden & West End",
    "Hyde Park & Kensington Gardens",
    "London Eye",
  ],
  barcelona: [
    "Sagrada Família",
    "Parc Güell",
    "Ramblas & quartier gothique",
    "Casa Batlló",
    "Casa Milà (La Pedrera)",
    "Plage de la Barceloneta",
    "Montjuïc & musée national d'art de Catalogne",
  ],
  madrid: [
    "Musée du Prado",
    "Palais royal de Madrid",
    "Parc du Retiro",
    "Plaza Mayor",
    "Puerta del Alcalá",
    "Gran Vía",
    "Marché San Miguel",
  ],
  malta: [
    "La Valette — Grand Harbour & Trois Cités (Birgu, Senglea, Bormla)",
    "Upper Barrakka Gardens & saluting battery",
    "Co-cathédrale Saint-Jean & rues de La Valette",
    "Mdina — cité silencieuse & remparts",
    "Temples mégalithiques d'Hagar Qim & Mnajdra (UNESCO)",
    "Grotte Bleue (Blue Grotto) & falaises Dingli",
    "Comino — Blue Lagoon & baie cristalline",
  ],
  rome: [
    "Colisée",
    "Forum romain & Palatin",
    "Fontaine de Trevi",
    "Panthéon",
    "Place Navone",
    "Chapelle Sixtine & Musées du Vatican",
    "Trinité-des-Monts & Escaliers d'Espagne",
  ],
  milan: [
    "Duomo & galerie Vittorio Emanuele II",
    "Cène de Vinci — Santa Maria delle Grazie",
    "Teatro alla Scala",
    "Château des Sforza",
    "Quartier Navigli",
    "Quadrilatère de la mode",
    "Pinacoteca di Brera",
  ],
  venise: [
    "Place Saint-Marc & basilique",
    "Palais des Doges",
    "Pont du Rialto",
    "Grand Canal en vaporetto",
    "Îles Murano & Burano",
    "Campanile de Saint-Marc",
    "Scala Contarini del Bovolo",
  ],
  berlin: [
    "Porte de Brandebourg",
    "Mur du Berlin & East Side Gallery",
    "Musée de Pergame",
    "Île aux Musées",
    "Reichstag & dôme",
    "Mémorial de l'Holocauste",
    "Alexanderplatz & Fernsehturm",
  ],
  amsterdam: [
    "Canaux & maisons annulaires",
    "Musée Van Gogh",
    "Rijksmuseum",
    "Maison d'Anne Frank",
    "Quartier du Jordaan",
    "Marché aux fleurs",
    "Dam & palais royal",
  ],
  bruxelles: [
    "Grand-Place",
    "Manneken Pis & quartier",
    "Atomium & Mini-Europe",
    "Musée Magritte",
    "Palais royal",
    "Place du Sablon & chocolatiers",
    "Arcades du Cinquantenaire",
  ],
  lisbonne: [
    "Alfama & château Saint-Georges",
    "Belém — Tour & monastère des Hiéronymites",
    "Tramway 28",
    "Baixa & Praça do Comércio",
    "LX Factory",
    "Miradouros (Santa Luzia, Senhora do Monte)",
    "Bairro Alto & Chiado",
  ],
  porto: [
    "Ribeira & pont Dom-Louis-I",
    "Caves de Porto (Vila Nova de Gaia)",
    "Livraria Lello",
    "Tour des Clercs",
    "Sé do Porto (cathédrale)",
    "Jardins du palais de Cristal",
    "Maison de la musique",
  ],
  prague: [
    "Pont Charles",
    "Château de Prague & cathédrale Saint-Guy",
    "Place de la Vieille-Ville & horloge astronomique",
    "Quartier juif Josefov",
    "Colline de Petřín",
    "Place Wenceslas",
    "Malá Strana & Lennon Wall",
  ],
  vienne: [
    "Palais de Schönbrunn",
    "Centre historique & cathédrale Saint-Étienne",
    "Hofburg",
    "Belvédère",
    "Naschmarkt",
    "Prater & grande roue",
    "Opéra d'État",
  ],
  budapest: [
    "Parlement sur le Danube",
    "Bains Széchenyi",
    "Château de Buda & bastion des pêcheurs",
    "Pont des Chaînes",
    "Basilique Saint-Étienne",
    "Andrássy & Maison de la terreur",
    "Grande synagogue de la rue Dohány",
  ],
  athenes: [
    "Acropole & Parthénon",
    "Agora antique",
    "Musée de l'Acropole",
    "Plaka & Anafiotika",
    "Temple de Zeus olympien",
    "Stade panathénaïque",
    "Colline Lycabette",
  ],
  istanbul: [
    "Sainte-Sophie (Ayasofya)",
    "Mosquée Bleue",
    "Palais de Topkapi",
    "Grand Bazar",
    "Croisière sur le Bosphore",
    "Citerne Basilique",
    "Tour de Galata",
  ],
  dubai: [
    "Burj Khalifa & Dubai Mall",
    "Fontaines de Dubai",
    "Palm Jumeirah & Atlantis",
    "Souk de Deira & creek en abra",
    "Quartier Al Fahidi",
    "Marina de Dubaï & JBR",
    "Musée du futur",
  ],
  doha: [
    "Musée d'art islamique",
    "Corniche & West Bay",
    "Souk Waqif",
    "Katara — village culturel",
    "The Pearl-Qatar",
    "Musée national du Qatar",
    "Msheireb Downtown",
  ],
  "abu dhabi": [
    "Grande mosquée Sheikh Zayed",
    "Louvre Abu Dhabi",
    "Corniche d'Abu Dhabi",
    "Qasr Al Watan",
    "Ferrari World — île Yas",
    "Heritage Village",
    "Observation Etihad Towers",
  ],
  "le caire": [
    "Pyramides de Gizeh & Sphinx",
    "Musée égyptien du Caire",
    "Khan el-Khalili",
    "Citadelle Saladin & mosquée Mohammed Ali",
    "Caire islamique & mosquée Ibn Touloun",
    "Croisière sur le Nil",
    "Quartier copte",
  ],
  marrakech: [
    "Place Jemaa el-Fna",
    "Médina & souks",
    "Palais Bahia",
    "Jardin Majorelle & musée Yves Saint Laurent",
    "Mosquée Koutoubia",
    "Palais El Badi",
    "Tombeaux saadiens",
  ],
  tunis: [
    "Médina de Tunis (UNESCO)",
    "Mosquée Zitouna",
    "Souks",
    "Carthage & musée",
    "Sidi Bou Saïd",
    "Musée national du Bardo",
    "Avenue Habib Bourguiba",
  ],
  alger: [
    "Casbah d'Alger",
    "Basilique Notre-Dame d'Afrique",
    "Jardin d'essai du Hamma",
    "Mémorial du Martyr (Maqam Echahid)",
    "Musée des antiquités & musée des Beaux-Arts",
    "Front de mer & plage Sidi Fredj",
    "Palais des Raïs (Bastion 23)",
  ],
  sydney: [
    "Opéra de Sydney & Circular Quay",
    "Harbour Bridge",
    "Bondi Beach & promenade côtière",
    "Jardin botanique royal",
    "The Rocks",
    "Ferry vers Manly",
    "Musée d'art contemporain",
  ],
  melbourne: [
    "Federation Square & gare Flinders Street",
    "Ruelles & cafés du CBD",
    "Queen Victoria Market",
    "Royal Botanic Gardens",
    "National Gallery of Victoria",
    "Plage St Kilda & jetée",
    "Melbourne Museum & Carlton Gardens",
  ],
  auckland: [
    "Sky Tower",
    "Waterfront & Viaduct Harbour",
    "Musée Auckland War Memorial",
    "Quartier Ponsonby",
    "One Tree Hill & parc Cornwall",
    "Ferry vers île Waiheke",
    "Auckland Domain & jardins d'hiver",
  ],
  "cape town": [
    "Table Mountain",
    "Cap de Bonne-Espérance",
    "Waterfront V&A",
    "Bo-Kaap",
    "Jardin botanique Kirstenbosch",
    "Robben Island",
    "Camps Bay & Chapman's Peak",
  ],
  "rio de janeiro": [
    "Corcovado — Christ Rédempteur",
    "Pain de Sucre",
    "Plages Copacabana & Ipanema",
    "Escalier Selarón",
    "Centre & Confeitaria Colombo",
    "Jardin botanique",
    "Maracanã",
  ],
  "sao paulo": [
    "Avenida Paulista & MASP",
    "Marché municipal",
    "Vila Madalena & Beco do Batman",
    "Parc Ibirapuera",
    "Quartier Liberdade",
    "Cathédrale de la Sé",
    "Pinacoteca",
  ],
  phuket: [
    "Grand Bouddha de Phuket",
    "Vieille ville Phuket",
    "Plage Patong & point de vue Karon",
    "Excursion îles Phi Phi",
    "Wat Chalong",
    "Cap Promthep & coucher de soleil",
    "Marché nocturne de Phuket",
  ],
  ibiza: [
    "Dalt Vila (vieille ville fortifiée)",
    "Plage de Cala Comte & coucher de soleil",
    "Es Vedrà & Cala d'Hort",
    "Playa d'en Bossa & clubs",
    "Marché hippie de Las Dalias",
    "Port d'Ibiza & quartier de la Marina",
    "Cala Salada & Cala Saladeta",
  ],
  mykonos: [
    "Petite Venise & moulins à vent",
    "Plage Paradise & Super Paradise",
    "Quartier de Chóra (vieille ville)",
    "Île de Délos (site archéologique)",
    "Plage d'Elia",
    "Église Panagia Paraportiani",
    "Ano Mera & monastère de la Panagia Tourliani",
  ],
  santorini: [
    "Village d'Oia & coucher de soleil",
    "Caldeira & randonnée Fira–Oia",
    "Plage Rouge (Red Beach)",
    "Akrotiri (site archéologique)",
    "Fira (capitale & musée)",
    "Plage de Kamari",
    "Vignobles de Santorini & dégustation",
  ],
  santorin: [
    "Village d'Oia & coucher de soleil",
    "Caldeira & randonnée Fira–Oia",
    "Plage Rouge (Red Beach)",
    "Akrotiri (site archéologique)",
    "Fira (capitale & musée)",
    "Plage de Kamari",
    "Vignobles de Santorini & dégustation",
  ],
  cancun: [
    "Ruines de Tulum (excursion)",
    "Isla Mujeres & Playa Norte",
    "Zone Hotelera & Playa Delfines",
    "Cenote Ik Kil ou Suytun",
    "Chichén Itzá (excursion)",
    "Parc Xcaret ou Xel-Há",
    "Marché 28 de Cancún",
  ],
  cannes: [
    "La Croisette & plages",
    "Palais des Festivals & allée des stars",
    "Suquet — vieux quartier & musée de la Castre",
    "Marché Forville",
    "Îles de Lérins (Sainte-Marguerite & Saint-Honorat)",
    "Port Canto & quartier du port",
    "Rue d'Antibes & shopping centre-ville",
  ],
  colmar: [
    "Petite Venise & quais de la Poissonnerie",
    "Musée Unterlinden",
    "Maison Pfister & maisons à colombages",
    "Koïfhus & place de l'Ancienne-Douane",
    "Quartier des tanneurs & rue des Serruriers",
    "Marché couvert & centre historique",
    "Route des vins & villages d'Alsace (excursion)",
  ],
  metz: [
    "Cathédrale Saint-Étienne & place d'Armes",
    "Centre Pompidou-Metz",
    "Place Saint-Louis & quartier impérial",
    "Porte des Allemands & remparts médiévaux",
    "Esplanade & quartier des arts",
    "Marché couvert & rue Serpenoise",
    "Plan d'eau & berges de la Moselle",
  ],
  mulhouse: [
    "Cité de l'automobile — collection Schlumpf",
    "Musée EDF Electropolis",
    "Temple Saint-Étienne — plus haute cathédrale de France",
    "Place de la Réunion & hôtel de ville",
    "Parc zoologique & botanique de Mulhouse",
    "Quartier Rebberg & villas Belle Époque",
    "Vieux Mulhouse & portes fortifiées",
  ],
  nancy: [
    "Place Stanislas — ensemble UNESCO",
    "Place de la Carrière & place d'Alliance",
    "Parc de la Pépinière",
    "Musée Lorrain & palais des ducs",
    "Vieille ville & porte de la Craffe",
    "École de Nancy — musée & villas Art nouveau",
    "Cathédrale Notre-Dame-de-l'Annonciation",
  ],
  reims: [
    "Cathédrale Notre-Dame & façade des rois",
    "Palais du Tau & trésor",
    "Basilique Saint-Remi",
    "Caves de champagne & maisons de négoce",
    "Place Drouet-d'Erlon & centre piéton",
    "Halles du Boulingrin",
    "Porte de Mars & cryptoportique gallo-romain",
  ],
  strasbourg: [
    "Cathédrale Notre-Dame de Strasbourg",
    "Grande Île — Petite France & ponts couverts",
    "Palais Rohan & musées (Beaux-Arts, archéologique)",
    "Place Kléber & centre piéton",
    "Parlement européen & quartier européen",
    "Parc de l'Orangerie",
    "Barrage Vauban & panorama sur la Petite France",
  ],
  valencia: [
    "Cité des arts et des sciences",
    "Lonja de la Seda (UNESCO)",
    "Marché Central & quartier Carmen",
    "Cathédrale & tour du Micalet (El Miguelete)",
    "Jardin du Turia & Gare du Nord restaurée",
    "Plage de la Malvarrosa & promenade maritime",
    "Albufera & paella (excursion)",
  ],
  florence: [
    "Duomo — Santa Maria del Fiore & baptistère",
    "Galerie des Offices (Uffizi)",
    "Ponte Vecchio & rives de l'Arno",
    "Piazzale Michelangelo (vue panoramique)",
    "Palais Pitti & jardins de Boboli",
    "Basilique Santa Croce",
    "Galerie de l'Académie (David de Michel-Ange)",
  ],
  berne: [
    "Vieille ville UNESCO — Zytglogge & arcades",
    "Fosse aux ours (BärenPark) & ponts sur l'Aar",
    "Bundeshaus (Parlement fédéral) & terrasse",
    "Rosengarten (vue sur la vieille ville)",
    "Musée d'Histoire & Maison Einstein",
    "Cathédrale (Berner Münster)",
    "Musée des beaux-arts (Kunstmuseum)",
  ],
  tulum: [
    "Ruines mayas de Tulum",
    "Plage de Tulum (sous les ruines)",
    "Gran Cenote",
    "Cenote Dos Ojos",
    "Réserve de Sian Ka'an",
    "Art & ruines de Coba",
    "Laguna de Bacalar (excursion)",
  ],
  stockholm: [
    "Gamla Stan (vieille ville)",
    "Musée Vasa (Vasamuseet)",
    "Palais royal & relève de la garde",
    "Hôtel de ville (Stadshuset) & vue sur Riddarfjärden",
    "Skansen — écomusée & zoo",
    "Quartier Södermalm & SoFo",
    "Archipel de Stockholm (excursion en bateau)",
  ],
  copenhague: [
    "Nyhavn & port pittoresque",
    "Tivoli Gardens",
    "Petite Sirène (Den lille havfrue)",
    "Château de Rosenborg & jardins",
    "Christiansborg — palais & Parlement",
    "Strøget & Hôtel de ville",
    "Marché couvert Torvehallerne",
  ],
  oslo: [
    "Parc Frogner & sculptures Vigeland",
    "Musée des navires vikings (Vikingskipshuset)",
    "Forteresse Akershus",
    "Opéra d'Oslo & promenade sur le toit",
    "Île des musées (Museumsøya)",
    "Palais royal & Karl Johans gate",
    "Quartier Grünerløkka",
  ],
  helsinki: [
    "Cathédrale luthérienne & place du Sénat",
    "Église Temppeliaukio (dans le rocher)",
    "Forteresse maritime Suomenlinna (UNESCO)",
    "Marché Kauppatori & halle couverte",
    "Musée national de Finlande",
    "Cathédrale orthodoxe Ouspenski",
    "Quartier Design & quai",
  ],
  dublin: [
    "Trinity College & Livre de Kells",
    "Temple Bar & quartier culturel",
    "Guinness Storehouse & Gravity Bar",
    "Château de Dublin",
    "Cathédrale Saint-Patrick",
    "Phoenix Park & Zoo",
    "O'Connell Street & General Post Office",
  ],
  naples: [
    "Centre historique de Naples (UNESCO)",
    "Musée archéologique national",
    "Cathédrale & trésor de San Gennaro",
    "Quartier Spaccanapoli & San Gregorio Armeno",
    "Castel dell'Ovo & bord de mer",
    "Castel Nuovo (Maschio Angioino)",
    "Pizza napolitaine — quartiers historiques",
  ],
  seville: [
    "Alcázar royal de Séville",
    "Cathédrale de Séville & Giralda",
    "Plaza de España & parc María Luisa",
    "Quartier Santa Cruz",
    "Torre del Or & Guadalquivir",
    "Metropol Parasol (Las Setas)",
    "Quartier Triana & bords du fleuve",
  ],
  turin: [
    "Mole Antonelliana & musée du cinéma",
    "Palais royal & Armeria Reale",
    "Place San Carlo & cafés historiques",
    "Musée égyptien",
    "Cathédrale Saint-Jean-Baptiste & Suaire",
    "Piazza Castello & palais Madama",
    "Église de la Consolata",
  ],
  warsaw: [
    "Vieille ville reconstruite (UNESCO)",
    "Château royal & place du Château",
    "Palais de la culture & des sciences",
    "Musée de l'insurrection de Varsovie",
    "Parc royal Lazienki & palais sur l'île",
    "Quartier Praga & cathédrale Saint-Florian",
    "Barbican & remparts médiévaux",
  ],
  krakow: [
    "Place du Marché (Rynek) & Sukiennice",
    "Château de Wawel & cathédrale",
    "Quartier juif Kazimierz & synagogues",
    "Porte Saint-Florian & Barbakan",
    "Mine de sel de Wieliczka (excursion)",
    "Collegium Maius (Université Jagellon)",
    "Boulevard Planty & église Sainte-Marie",
  ],
  edinburgh: [
    "Château d'Édimbourg",
    "Royal Mile — Holyroodhouse à Castle Rock",
    "Arthur's Seat & Salisbury Crags",
    "Palais de Holyroodhouse",
    "Grassmarket & Victoria Street",
    "National Museum of Scotland",
    "Calton Hill & monuments",
  ],
  palermo: [
    "Cathédrale de Palerme",
    "Palais des Normands & chapelle Palatine",
    "Teatro Massimo",
    "Marché Ballarò",
    "Quartier Kalsa & Piazza Marina",
    "Catacombes des Capucins",
    "Monreale — cathédrale & cloître (excursion)",
  ],
  visby: [
    "Remparts médiévaux (Ringmur) — promenade sur les murs",
    "Cathédrale Sainte-Marie (Sankta Maria domkyrka)",
    "Ruines d'églises médiévales (Sankta Karin, Sankta Lars…)",
    "Gotlands museum — histoire viking & hanséatique",
    "Almedalen & front de mer hanséatique",
    "Place Stora torget & ruelles pavées de la vieille ville",
    "Île de Gotland — phare de Högklint ou plages au sud (excursion)",
  ],
};

/** Clés alias (Wikimedia / saisie) → entrée canonique : mêmes libellés, zéro repli générique. */
const ICONIC_PLACE_ALIAS_TO_BASE = [
  ["barcelone", "barcelona"],
  ["londres", "london"],
  ["roma", "rome"],
  ["firenze", "florence"],
  ["milano", "milan"],
  ["venice", "venise"],
  ["bern", "berne"],
  ["lisbon", "lisbonne"],
  ["vienna", "vienne"],
  ["athens", "athenes"],
  ["myconos", "mykonos"],
  ["nyc", "new york"],
  ["cairo", "le caire"],
  ["eivissa", "ibiza"],
  ["canton", "guangzhou"],
  ["kwangchow", "guangzhou"],
  ["pekin", "beijing"],
  ["malte", "malta"],
  ["copenhagen", "copenhague"],
  ["kobenhavn", "copenhague"],
  ["napoli", "naples"],
  ["sevilla", "seville"],
  ["séville", "seville"],
  ["torino", "turin"],
  ["cracovie", "krakow"],
  ["varsovie", "warsaw"],
  ["warszawa", "warsaw"],
  ["edinbourg", "edinburgh"],
  ["gotland", "visby"],
];
for (const [alias, base] of ICONIC_PLACE_ALIAS_TO_BASE) {
  const src = ICONIC_PLACES_CANONICAL[base];
  if (src) ICONIC_PLACES_CANONICAL[alias] = src;
}
